_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 71
                - 83
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 71
                - 83
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
ckpt_every:
    value: 6000
data_path:
    value: /NAS/Data/imagenet_trucks
epochs:
    value: 1400
global_batch_size:
    value: 128
global_seed:
    value: 0
image_size:
    value: 256
log_every:
    value: 100
model:
    value: DiT-S/2
num_classes:
    value: 1
num_workers:
    value: 4
results_dir:
    value: /NAS/kian/DiT
vae:
    value: ema
